name: Build Documentation

on:
  push:
    paths:
      - '.github/workflows/publish-docs.yml'
      - 'docs/*'
      - 'package.json'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Installing NPM deps
        run: npm install

      - name: Build documentation
        run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
        